print(not True)
print(not False)
print('NOT AND')
print('not True and True => ', not (True and True))
print('not True and False =>', not (True and False))
print('not False and False', not (False and False))
print('not 10 > 5 and 5 < 10 => ', not (10 > 5 and 5 < 10))
print('not 10 > 5 and 10 < 5 => ', not (10 > 5 and 10 < 5))
